config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root "welcome#index"
  resources :orders
  resources :users

  get '/orders' => "orders#index", as: :user_root

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :locomotive
  belongs_to :contact_person, optional: true
  belongs_to :executor,
              class_name: "User",
              foreign_key: :executor_id,
              optional: true

  accepts_nested_attributes_for :contact_person, reject_if: :all_blank

  enum status: [:newborn, :in_progress, :completed, :canceled]

  before_save :set_in_progress, if: [:newborn?, :assigned?]

  private

  def set_in_progress
    self.status = :in_progress
  end

  def assigned?
    executor.present?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :check_manager, except: %i[ index show ]

  # GET /orders or /orders.json
  def index
    @orders = Order.includes(:executor, :locomotive)
    if current_user.manager?
      @orders = @orders.all
    else 
      @orders = @orders.where(executor: current_user).in_progress
    end

  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.build_contact_person
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        @order.build_contact_person unless @order.contact_person
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:city, :locomotive_id, :budget, :diem, :housing, :rental_housing, :tangen, :cup, :wheel_pairs, :start_date, :executor_id, contact_person_attributes: [:id, :name, :patronymic, :surname, :phone])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
= form_with(model: @order, builder: CustomFormBuilder) do |form|
  .form-floating.mb-2
    = form.text_field :city, placeholder: :city
    = form.label :city

  .form-floating.mb-2
    = form.select :locomotive_id, Locomotive.all.collect { |l| [l.model, l.id] }
    = form.label :locomotive_id

  .form-floating.mb-2
    = form.number_field :wheel_pairs, placeholder: :wheel_pairs
    = form.label :wheel_pairs

  
  .form-group 
    .row
      .col
        .form-floating.mb-2
          = form.number_field :budget, placeholder: :budget
          = form.label :budget

      .col
        .form-floating.mb-2
          = form.number_field :diem, placeholder: :diem
          = form.label :diem

      .col 
        .form-floating.mb-2
          = form.number_field :rental_housing, placeholder: :rental_housing
          = form.label :rental_housing
  
  .form-floating.mb-2
    = form.text_field :housing, placeholder: :housing
    = form.label :housing

  .input-group.mb-2
    span.input-group-text = Order.human_attribute_name :incisors
    .form-floating
      = form.number_field :tangen, placeholder: :tangen
      = form.label :tangen
    .form-floating
      = form.number_field :cup, placeholder: :cup
      = form.label :cup


  .card.mb-2.text-bg-light
    .card-body
      = form.fields_for :contact_person do |person_form|
        .input-group.mb-2
          span.input-group-text = ContactPerson.model_name.human
          .form-floating
            = person_form.phone_field :phone, placeholder: :phone
            = person_form.label :phone

        .input-group
          .form-floating
            = person_form.text_field :surname, placeholder: :surname
            = person_form.label :surname

          .form-floating
            = person_form.text_field :name, placeholder: :name
            = person_form.label :name

          .form-floating
            = person_form.text_field :patronymic, placeholder: :patronymic
            = person_form.label :patronymic
    
  .row.mb-2
    .col
      .form-floating.mb-2
        = form.date_field :start_date
        = form.label :start_date

    .col
      .form-floating.mb-2
        = form.select :executor_id,
          User.executor.collect { |e| ["#{e.name} #{e.surname}", e.id]},
          include_blank: true
        = form.label :executor_id

  .mb-2
    = form.submit class: "btn btn-primary"

app/views/orders/_order.html.slim
tr id="#{dom_id order}"
  td 
    span title = Order.human_attribute_name("status.#{order.status}")
      - case order.status.to_sym
      - when :newborn
        i.bi.bi-circle
      - when :in_progress
        i.bi.bi-person-circle 
      - when :completed
        i.bi.bi-check-circle
      - else
        i.bi.bi-x-circle
  td = link_to "#{Order.model_name.human} №#{order.id}", order, class: "d-block"
  td = order.locomotive.model
  td = order.city

app/views/orders/edit.html.slim
.container 
  .row.justify-content-center
    .col.col-sm-10.col-md-8.col-lg-6.col-xl-4 
      h1 = t :edit, scope: [:navigation, :orders]

      == render "form", order: @order

      br

      div
        => link_to t(:show, scope: [:helpers, :actions],
                            model: Order.model_name.human),
                  @order
        '|
        =< link_to t("navigation.back"), orders_path

app/views/orders/index.html.slim
.container 
  .row
    .col
      h1 = t :title, scope: [:navigation, :orders]

      table.table#orders
        tbody
          - @orders.each do |order|
            == render order
      
      - if current_user.manager?
        = link_to t(:new, scope: [:helpers, :actions],
                          model: Order.model_name.human),
                  new_order_path,
                  class: "btn btn-primary"

app/views/orders/new.html.slim
.container 
  .row.justify-content-center
    .col.col-sm-10.col-md-8.col-lg-6.col-xl-4 
      h1 = t :new, scope: [:navigation, :orders]

      == render "form", order: @order

      br

      div
        = link_to t("navigation.back"), orders_path

app/views/orders/show.html.slim
.container 
  .row.justify-content-center
    .col.col-sm-10.col-md-8.col-lg-6.col-xl-4 
      h3 = "#{Order.model_name.human} №#{@order.id}"

      .card 
        .card-body
          dl.row.mb-0
            dt.col-5 = Order.human_attribute_name :city
            dd.col-7 = @order.city

            dt.col-5 = Locomotive.human_attribute_name :model
            dd.col-7 = @order.locomotive.model

            dt.col-5 = Order.human_attribute_name :housing
            dd.col-7 = @order.housing

            dt.col-5 = Order.human_attribute_name :executor_id
            dd.col-7
              - if @order.executor.present?
                = @order.executor.full_name
              - else 
                = Order.human_attribute_name :not_assigned

      .card 
        .card-body
          h5.card-title = ContactPerson.model_name.human
          dl.row.mb-0
            - if @order.contact_person.present?
              dt.col-5 = ContactPerson.human_attribute_name :full_name
              dd.col-7 = @order.contact_person.full_name

              dt.col-5 = ContactPerson.human_attribute_name :phone
              dd.col-7 = @order.contact_person.phone

      .card
        .card-body 
          h5.card-title = Order.human_attribute_name :budget
          table.table 
            thead 
              th = Order.human_attribute_name :allocated
              th = Order.human_attribute_name :rest
            tbody 
              tr
                td = @order.budget
                td = @order.budget

      .card 
        .card-body 
          h5.card-title = Order.human_attribute_name :incisors
          table.table 
            thead 
              th 
              th = Order.human_attribute_name :allocated
              th = Order.human_attribute_name :rest
            tbody 
              tr
                th = Order.human_attribute_name :tangen
                td = @order.tangen
                td = @order.tangen
              tr 
                th = Order.human_attribute_name :cup
                td = @order.cup
                td = @order.cup

      .card
        .card-body
          h5.card-title = Order.human_attribute_name :wheel_pairs
          table.table 
            thead 
              th = Order.human_attribute_name :allocated
              th = Order.human_attribute_name :rest
            tbody 
              tr
                td = @order.wheel_pairs
                td = @order.wheel_pairs


      br
      div
        =< link_to t("navigation.back"), orders_path
        - if current_user.manager?
          '|
          => link_to t(:edit, scope: [:helpers, :actions],
                              model: Order.model_name.human),
                    edit_order_path(@order)
          br
          br
          = button_to t(:destroy, scope: [:helpers, :actions],
                                  model: Order.model_name.human),
                      @order,
                      method: :delete,
            class: "btn btn-danger"
        - else 
          br
          br
          = link_to t(:fill_in, scope: [:helpers, :actions],
                              model: "Report"),
                    nil,
                    class: "btn btn-warning disabled"
        br
        br