config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root "welcome#index"
  resources :orders
  resources :users

  get '/orders' => "orders#index", as: :user_root

end

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-expand-sm
  .container
    = link_to t(:app_name), root_path, class: "navbar-brand"
    - if user_signed_in?
      button.navbar-toggler type="button" data-bs-toggle="collapse"data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded=false aria-labe="Toggle navigation"
        span.navbar-toggler-icon
      #navbar-menu.collapse.navbar-collapse
        ul.navbar-nav.me-auto
          li.nav-item
            = link_to t("navigation.orders.title"), orders_url, class: "nav-link #{"active" if controller_name == "orders"}"
          - if current_user.manager?
            li.nav-item
              = link_to t("navigation.users.title"), users_url, class: "nav-link #{"active" if controller_name == "users"}"

        ul.navbar-nav
          li.nav-item
            = link_to "#{current_user.name} #{current_user.surname}", nil,
              class: "nav-link disabled"
          li.nav-item
            = link_to t("navigation.log_out"), destroy_user_session_path,  data: { 'turbo-method': :delete }, class: "btn btn-outline-primary"

    - else
      ul.navbar-nav.me-auto
      ul.navbar-nav
        li.nav-item
          = link_to t("navigation.log_in"), new_user_session_path, class: "btn btn-outline-primary"

hr

app/views/layouts/_notice.html.slim
.container
  .row.justify-content-center
    .col-10.col-sm-8.position-relative
      br  
      - [:notice, :alert, :error, :info].each do |name|
        - if flash[name].present?
          #notice.alert.alert-dismissible.fade.show *{ class: flash_class(name),
                                                       role: alert}
            
            = flash[name].html_safe
            
            button.btn-close *{ data: { bs: { dismiss: 'alert' } },
                                aria: { label: 'Close' } }

app/views/layouts/application.html.slim
doctype html
html
  head
    title 
      = t :app_name
    meta[name="viewport" content="width=device-width,initial-scale=1"]

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", "defer": true

    = favicon_link_tag "favicon.jpg", type: "image/jpg", "data-turbo-track": "reload"

  body
    = render "layouts/navigation"
    = render "layouts/notice"

    = yield